### ISSUE TITLE
if Open Data then not custom

### ISSUE THREAD

**Issue by federicomorando** [bassosimone/yucca-hookka#1]
thanks to @bassosimone for the license related features, but I'd like to implement a situation where:
- if "Open Data" == true, then "Custom License" == false (and possibly the radio button disappears: no custom open data licenses will be available);
- if "Open Data" == false, then "Custom License" == true (by default) and there is in any case an option to combine a set of "standard" elements together + the custom license URL, in other words, you choose a custom license, but you also describe it using some custom tags
  - update: we could use "License Restrictions" to describe the custom licence using tags, while we could automatically generate the tags "Attribution" and "Share Alike" for the standard Open Data licenses (in the sense that, there, you cannot choose custom restrictions, but one or two are automatically added).

**Comment by bassosimone** [comment]
Any commit after c6d6f4c6b included should contain an implementation of this.
